-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    nome character varying(125) NOT NULL,
    email text NOT NULL,
    senha text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.post
(
    id serial NOT NULL,
    user_id serial NOT NULL,
    content text NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.post
    ADD CONSTRAINT "ID_Usuario" FOREIGN KEY (user_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

INSERT INTO public.usuarios(nome, email, senha)
	VALUES ('lucas', 'lucas@gmail.com', '123456');

select * from usuarios

END;